#!/usr/bin/env -S expect -f

set force_conservative 0

if {$force_conservative} {
	set send_slow {1 .1}
	proc send {ignore arg} {
		sleep .1
		exp_send -s -- $arg
	}
}

set timeout 3
spawn ../../bin/conventional-commits config --config ../configs/config-03.json --dump
match_max 100000

expect -exact "{\r
    \"typeCase\": \"lower\",\r
    \"types\": \[\r
        \"foo\",\r
        \"bar\"\r
    \],\r
    \"scopeCase\": \"snake\",\r
    \"scopeRequired\": true,\r
    \"scopes\": \[\r
        \"baz\",\r
        \"qux\"\r
    \],\r
    \"descriptionCase\": \"sentence\",\r
    \"descriptionEndMark\": \".\",\r
    \"bodyRequired\": true,\r
    \"bodyWrapWidth\": 72,\r
    \"requiredFooters\": \[\r
        \"See-also\",\r
        \"Signed-off-by\"\r
    \]\r
}"
expect eof
