#!/usr/bin/env -S expect -f

set force_conservative 0

if {$force_conservative} {
	set send_slow {1 .1}
	proc send {ignore arg} {
		sleep .1
		exp_send -s -- $arg
	}
}

set timeout 3
spawn ../../bin/conventional-commits config --config ../configs/config-02.json --dump
match_max 100000

expect -exact "{\r
    \"typeCase\": null,\r
    \"types\": \[\],\r
    \"scopeCase\": null,\r
    \"scopeRequired\": false,\r
    \"scopes\": \[\],\r
    \"descriptionCase\": null,\r
    \"descriptionEndMark\": null,\r
    \"bodyRequired\": false,\r
    \"bodyWrapWidth\": null,\r
    \"requiredFooters\": \[\]\r
}"
expect eof
