#!/usr/bin/env -S expect -f

set force_conservative 0

if {$force_conservative} {
	set send_slow {1 .1}
	proc send {ignore arg} {
		sleep .1
		exp_send -s -- $arg
	}
}

set timeout 3
spawn ../../bin/conventional-commits prepare --config ../configs/default.json
match_max 100000

expect -exact "\r
\[33mPrepare Commit Message\[39m\r
\[33m======================\[39m\r
\r
 The following prompts will help you create a commit message that\r
 follows the Conventional Commits specification.\r
\r
 \[32mWhat is the type of change you're committing? (e.g., feat, fix, etc.)\[39m \[\[33mfeat\[39m\]:\r
 > "
send -- "f"
expect -exact "f\[K7\[30;47meat\[39;49m8"
send -- "	"
expect -exact "eat"
send -- "\r"
expect -exact "\r
\r
 \[32mWhat is the scope of this change (e.g., component or file name)?\[39m:\r
 > "
send -- "\r"
expect -exact "\r
\r
 \[32mWrite a short description of the change\[39m:\r
 > "
send -- "this is a test\r"
expect -exact "this is a test\r
\r
 \[32mYou may provide a longer description of the change (press \[39m\[33mCtrl+D\[39m\[32m to continue)\[39m:\r
 > "
send -- "\r"
expect -exact "\r
\r
 \[32mAre there any breaking changes? (yes/no)\[39m \[\[33mno\[39m\]:\r
 > "
send -- "\r"
expect -exact "\r
\r
 \[32mDoes this change affect any open issues? (yes/no)\[39m \[\[33mno\[39m\]:\r
 > "
send -- "\r"
expect -exact "\r
\r
 \[32mWould you like to add any footers? (e.g., Signed-off-by, See-also) (yes/no)\[39m \[\[33mno\[39m\]:\r
 > "
send -- "\r"
expect -exact "\r
\[33mCommit Message\[39m\r
\[33m--------------\[39m\r
\r
 feat: this is a test"
expect eof
