#!/usr/bin/env -S expect -f

set force_conservative 0

if {$force_conservative} {
	set send_slow {1 .1}
	proc send {ignore arg} {
		sleep .1
		exp_send -s -- $arg
	}
}

set timeout 3
spawn ../../bin/conventional-commits prepare --config ../configs/default.json
match_max 100000

expect -exact "\r
\[33mPrepare Commit Message\[39m\r
\[33m======================\[39m\r
\r
 The following prompts will help you create a commit message that\r
 follows the Conventional Commits specification.\r
\r
 \[32mWhat is the type of change you're committing? (e.g., feat, fix, etc.)\[39m \[\[33mfeat\[39m\]:\r
 > "
send -- "f"
expect -exact "f\[K7\[30;47meat\[39;49m8"
send -- "i"
expect -exact "i\[K7\[30;47mx\[39;49m8"
send -- "	"
expect -exact "x"
send -- "\r"
expect -exact "\r
\r
 \[32mWhat is the scope of this change (e.g., component or file name)?\[39m:\r
 > "
send -- "config\r"
expect -exact "config\r
\r
 \[32mWrite a short description of the change\[39m:\r
 > "
send -- "use the correct config value\r"
expect -exact "use the correct config value\r
\r
 \[32mYou may provide a longer description of the change (press \[39m\[33mCtrl+D\[39m\[32m to continue)\[39m:\r
 > "
send -- "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eget ullamcorper velit. Mauris ornare vulputate leo. Ut tempus molestie egestas. Donec metus ligula, gravida sit amet eros nec, sollicitudin tristique eros. Nunc vestibulum lacinia mi, quis cursus orci tempor in."
expect -exact "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eget ullamcorper velit. Mauris ornare vulputate leo. Ut tempus molestie egestas. Donec metus ligula, gravida sit amet eros nec, sollicitudin tristique eros. Nunc vestibulum lacinia mi, quis cursus orci tempor in."
send -- "\r"
expect -exact "\r
"
send -- "\r"
expect -exact "\r
"
send -- "Aliquam felis ex, pretium at elit dapibus, vehicula congue justo. Maecenas nulla dui, dignissim ac blandit sed, vulputate in tortor. Fusce sed libero eros. Aliquam velit metus, pellentesque non enim sit amet, fermentum blandit tellus. Donec nibh augue, feugiat at cursus a, convallis id massa. Sed egestas leo a vulputate rhoncus."
expect -exact "Aliquam felis ex, pretium at elit dapibus, vehicula congue justo. Maecenas nulla dui, dignissim ac blandit sed, vulputate in tortor. Fusce sed libero eros. Aliquam velit metus, pellentesque non enim sit amet, fermentum blandit tellus. Donec nibh augue, feugiat at cursus a, convallis id massa. Sed egestas leo a vulputate rhoncus."
send -- "\r"
expect -exact "\r
"
send -- "\r"
expect -exact "\r
"
send -- "Cras eu egestas odio. Etiam non urna quam. Mauris nulla orci, placerat in malesuada nec, sagittis id enim. Sed viverra accumsan ligula in imperdiet. Aenean pretium faucibus erat non molestie. Mauris sed nibh mauris. Nunc ut fermentum felis."
expect -exact "Cras eu egestas odio. Etiam non urna quam. Mauris nulla orci, placerat in malesuada nec, sagittis id enim. Sed viverra accumsan ligula in imperdiet. Aenean pretium faucibus erat non molestie. Mauris sed nibh mauris. Nunc ut fermentum felis."
send -- "\r"
expect -exact "\r
"
send -- ""
expect -exact "^D\r
 \[32mAre there any breaking changes? (yes/no)\[39m \[\[33mno\[39m\]:\r
 > "
send -- "yes\r"
expect -exact "yes\r
\r
 \[32mDescribe the breaking changes\[39m:\r
 > "
send -- "Lorem ipsum dolor sit amet"
expect -exact "Lorem ipsum dolor sit amet"
send -- "\r"
expect -exact "\r
\r
 \[32mDoes this change affect any open issues? (yes/no)\[39m \[\[33mno\[39m\]:\r
 > "
send -- "yes\r"
expect -exact "yes\r
\r
 \[32mWhat is the issue reference type? (e.g., fix, re)\[39m:\r
 > "
send -- "fix\r"
expect -exact "fix\r
\r
 \[32mEnter the issue identifier \[39m\[33m(do not include a preceding #-symbol)\[39m:\r
 > "
send -- "4001\r"
expect -exact "4001\r
\r
 \[32mWhat is the issue reference type? (e.g., fix, re)\[39m:\r
 > "
send -- "re\r"
expect -exact "re\r
\r
 \[32mEnter the issue identifier \[39m\[33m(do not include a preceding #-symbol)\[39m:\r
 > "
send -- "5001\r"
expect -exact "5001\r
\r
 \[32mWhat is the issue reference type? (e.g., fix, re)\[39m:\r
 > "
send -- "\r"
expect -exact "\r
\r
 \[32mWould you like to add any footers? (e.g., Signed-off-by, See-also) (yes/no)\[39m \[\[33mno\[39m\]:\r
 > "
send -- "yes\r"
expect -exact "yes\r
\r
 \[32mTo add a footer, provide a footer name, or press ENTER to skip (e.g., Signed-off-by)\[39m:\r
 > "
send -- "See-also\r"
expect -exact "See-also\r
\r
 \[32mProvide a value for the footer See-also\[39m:\r
 > "
send -- "https://example.com/foo\r"
expect -exact "https://example.com/foo\r
\r
 \[32mTo add a footer, provide a footer name, or press ENTER to skip (e.g., Signed-off-by)\[39m:\r
 > "
send -- "\r"
expect eof
