# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<-SCRIPT
choco install git composer php unzip --no-progress -y
Invoke-WebRequest -Uri https://windows.php.net/downloads/pecl/releases/pcov/1.0.6/php_pcov-1.0.6-7.4-nts-vc15-x64.zip -UseBasicParsing -OutFile C:\\temp\\php_pcov.zip
unzip C:\\temp\\php_pcov.zip -d C:\\temp\\php_pcov
move C:\\temp\\php_pcov\\php_pcov.dll C:\\tools\\php74\\ext\\php_pcov.dll
Add-Content C:\\tools\\php74\\php.ini "`nextension=gmp"
Add-Content C:\\tools\\php74\\php.ini "`nextension=sodium"
Add-Content C:\\tools\\php74\\php.ini "`nextension=pcov"
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "jborean93/WindowsServer2019"
  config.vm.provision "shell", inline: $script
  config.vm.synced_folder "../../../", "C:\\Users\\vagrant\\conventional-commits"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "ramsey-conventional-commits-windows"
  end
end
